### ISSUE TITLE
italforniusa.com/technical-support

### ISSUE THREAD

**Issue by ItalforniUSA** [ItalforniUSAInc/Issues#12]
what happened to the link to www.italforniusa.com/technical-support page that was on the main navigation bar? we need this back up and functioning asap

**Comment by jigish-addweb** [comment]
We have made changes as per issue #5 from github and removed “Support” link from Main navigation.
Now we have added “Support” link back on navigation. 
And new created “Newsletter” page link is moved to footer links.

**Comment by ItalforniUSA** [comment]
Perfect thank you!
