### ISSUE TITLE
http://italforniusa.com/news

### ISSUE THREAD

**Issue by ItalforniUSA** [ItalforniUSAInc/Issues#4]
![news](https://cloud.githubusercontent.com/assets/18717756/14933439/d8c6866e-0e43-11e6-8a5e-cfc11670fb9f.png)
1. The events listed 3rd and 4th need to be removed.
2. Publishing dates do not need to be underneath the name of the event - remove this 
3. Update the information of the Pizza Expo event from 2016 dates to 2017 dates - the booth number and the location are the same as what is already written there.

**Comment by ItalforniUSA** [comment]
1. The events listed 3rd and 4th need to be removed.
2. Publishing dates do not need to be underneath the name of the event - remove this 
3. Update the information of the Pizza Expo event from 2016 dates to 2017 dates - the booth number and the location are the same as what is already written there.

**Comment by jigish-addweb** [comment]
Do we need to display only 2 items on news page, or we need to display two items per page with pagination ?

**Comment by ItalforniUSA** [comment]
We only have 2 events to display at the moment 

```
                                                                                   Nick Zaytsev / GM 
```

 zaytsenk@italforniusa.com / (859) 230-9962   Italforni USA 
 Office:  (424) 364-0075  / Fax:  (844) 273-6873 
 24418 S. Main St. Suite 408  Carson, CA 90745 
 www.italforniusa.com
